//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.28 at 10:00:02 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/Product", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
//@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/Product")
package org.example.product;
